#!/usr/bin/env bash

if [ -z $BEGIN ];
then
	RUN_DIR=${RUN_DIR-$(cd $(dirname .);pwd)}
	GATHER_CMD=${GATHER_CMD-$(readlink -f $0)}
	BEGIN=${BEGIN-"true"}
	export RUN_DIR
	export GATHER_CMD
	export BEGIN
else
fi


if [ -z $BEGIN ];
then
	local _pwdpath=$(pwd)
        for i in $(cat .gather.list)
        do
		cd $_pwdpath
		i=$(readlink -f $i)
                if [ -f "$i" ];
                then
                        rsync -aLr $i .
                fi
                if [ -d "$i" ];
                then
                        _basename=$(basename $i)
			[ -d "$basename" ] || mkdir $basename
			cd $basename
                        $GATHER_CMD
                fi
        done
else
	pwdpath=$(pwd)
	for i in $(ls -A .|awk '{print "'$pwd'"/$0}')
	do
		if [ -f "$i" ];
			rsync -aLr --delete $i .
		then
		fi

		if [ -d "$i" ];
		then
			cd $i;
		$GATHER_CMD 
		fi
		if ["$i" = ".gather.list" ];
		then
		continue
		fi
	done
fi
