#!/usr/bin/env bash

DIR=$(cd $(dirname .);pwd)
#echo "gather do $DIR"
from_dir=${2-$DIR}
to_dir=${3-$DIR}
from_dir=$(dirname $from_dir)/$(basename $from_dir)
to_dir=$(dirname $to_dir)/$(basename $to_dir)
cd $from_dir
echo $from_dir "to" $to_dir

gatherlist=$(ls -A)
if [ -f "${DIR}/.gather.list" ];
then
	gatherlist=$(cat ${DIR}/.gather.list|grep -v "#"|sed '/^\s*$/d')
fi

for i in $gatherlist;
do
	if [ -d $i ];
	then
		i=$(cd $i;pwd)
		if [ -f "$i/.gather.list" ];
		then
			/data/src/gather/gather $i $to_dir
			#echo $i,$to_dir
		else
			echo "dir:cp -frL $i $to_dir/"
			#rsync -aLr --delete --exclude
		fi
	else
		echo "file:cp -f $i $to_dir/"
	fi
done
