#!/usr/bin/env bash
#
dir=$(cd $(dirname .);pwd)
GATHER_CMD=$dir/gather2
export GATHER_CMD

from_path=${1-$dir}
to_path=${2-$dir}


dogather(){
	local _from_path=$(readlink -f $1)
	local _to_path=$(readlink -f $2)
	local _gatherlist=`gatherlist $_from_path`
	echo  ">>" $1 , $2  >&2
	echo  $_from_path , $_to_path >&2
	cd $_from_path
	for i in $_gatherlist
	do
		_diri=$(readlink -f $i)
		_basename=$(basename $_from_path)
		if [ -f "$i" ];
		then
			#echo "file:rsync -aLr --delete $i $_to_path/" >&2
			_basename=$(basename $(dirname $i))
			[ -d $_to_path/$_basename ] || mkdir -p $_to_path/$_basename
			rsync -aLr --delete $i $_to_path/$_basename
		else
			if [ ! -f "$i/.gather.list" ];
			then
				echo "dir:rsync -aLr --delete $_diri $_to_path/$_basename" >&2
				rsync -aLr --delete $_diri $_to_path/$_basename
			else
				echo "(dogather $_diri $_to_path/$_basename)" >&2
				[ -d $_to_path/$_basename ] || mkdir -p $_to_path/$_basename
				`(dogather $_diri $_to_path/$_basename)`
			fi
		fi
		
	done
}

dogatherlist(){
	local _from_path=$1
	#local _gatherlist=$(ls -A $_from_path|awk '{print "'$_from_path'/"$0}')
	#echo ${$gatherlist[*]}
	echo $_from_path
}

dogatherfilelist(){
	local _from_path=$1
	echo $_from_path
	echo ${_gatherlist[*]}
	if [ -f "$_from_path/.gather.list" ];
	then
		_gatherlist=$(cat $_from_path/.gather.list|grep -v "#"|sed '/^\s*$/d')
		echo ${_gatherlist[*]}
	fi
}

#echo "(`gatherlist $from_path`)"

result=(`dogather $from_path $to_path`)
echo ${result[*]}

