#!/usr/bin/env bash

START_DIR=$(cd $(dirname .);pwd)
filter=${1-*}
MMSTORE_HOME=${MMSTORE_HOME-$(pwd)}
if [ ! -f $MMSTORE_HOME/.mmstore.list ];
then
	echo "ERROR:.mmstore.list is not existed"
	exit
fi
cd $MMSTORE_HOME

lists=$(cat $MMSTORE_HOME/.mmstore.list|grep -v "#"|grep -E "$filter"|sed '/^\s*$/d')
for i in ${lists[*]}
do
	_real_fullpath=$i
	_relative_fullpath=${_real_fullpath#/}
	_real_fulldir=$(dirname $_real_fullpath)/
	_target_real_fullpath=$MMSTORE_HOME/$_relative_fullpath
	[ -f "$_target_real_fullpath/.mmstore.ignore" ] && _exclude_paths=$(cat $_target_real_fullpath/.mmstore.ignore |grep -v "#"|grep -E "$filter"|sed '/^\s*$/d')
	_exclude_append=""
	if [ -n "$_exclude_paths" ];
	then
		for t in ${_exclude_paths[@]}
		do
			_exclude_append="--exclude "$t
		done
	fi
	
	[ -e $_target_real_fullpath ] || continue
	[ -f $_target_real_fullpath ] && [ ! -f $_real_fullpath ] && rm -fr $_real_fullpath
	[ -d $_target_real_fullpath ] && [ ! -d $_real_fullpath ] && rm -fr $_real_fullpath
	_dirname=$(dirname $_real_fullpath)
	[ ! -e "$_dirname" ] && mkdir -p $_real_fullpath
	if [ -d $_target_real_fullpath ];
	then
		echo "rsync -aLr --delete $_target_real_fullpath $_real_fulldire$_exclude_append"
		rsync -aLr --delete $_target_real_fullpath $_real_fulldir $_exclude_append
	fi
	if [ -f $_target_real_fullpath ];
	then
		echo "rsync -aLr --delete $_target_real_fullpath $_real_fullpath $_exclude_append"
		rsync -aLr --delete $_target_real_fullpath $_real_fullpath $_exclude_append
	fi
done
